/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-05-11 09:02:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.MainPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class customerSupport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1743573402475L));
    _jspx_dependants.put("jar:file:/D:/workspaces/pj/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 최성현 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>3부상조 - 로그인</title>\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<!-- CSS 파일 링크 -->\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("	.privacy-container {\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif;\n");
      out.write("            background-color: #fff;\n");
      out.write("            color: #333;\n");
      out.write("            line-height: 1.6;\n");
      out.write("            max-width: 800px;\n");
      out.write("            margin: 120px auto 50px; /* 헤더 높이(80px) + 여백 조정 */\n");
      out.write("            padding: 40px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("        .privacy-container h1 {\n");
      out.write("            font-size: 2.2em;\n");
      out.write("            color: #2c3e50;\n");
      out.write("            text-align: center;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("        .privacy-container h2 {\n");
      out.write("            font-size: 1.5em;\n");
      out.write("            color: #34495e;\n");
      out.write("            margin-top: 30px;\n");
      out.write("            border-bottom: 2px solid #3498db;\n");
      out.write("            padding-bottom: 10px;\n");
      out.write("        }\n");
      out.write("        .privacy-container p, .privacy-container li {\n");
      out.write("            font-size: 1em;\n");
      out.write("            color: #4a4a4a;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("        .privacy-container ul {\n");
      out.write("            padding-left: 20px;\n");
      out.write("        }\n");
      out.write("        .privacy-container li {\n");
      out.write("            list-style-type: disc;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("        .privacy-container .highlight {\n");
      out.write("            background-color: #e8f4f8;\n");
      out.write("            padding: 15px;\n");
      out.write("            border-left: 4px solid #3498db;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            border-radius: 4px;\n");
      out.write("        }\n");
      out.write("        .privacy-container .footer {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 40px;\n");
      out.write("            font-size: 0.9em;\n");
      out.write("            color: #7f8c8d;\n");
      out.write("        }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- Header -->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/jsp/Header.jsp", out, false);
      out.write("\n");
      out.write("	<main>\n");
      out.write("		<div class=\"privacy-container\">\n");
      out.write("            <h1>고객지원</h1>\n");
      out.write("            <p>주식회사 인사플랫폼은 고객의 문의와 문제를 신속하고 친절하게 해결하기 위해 최선을 다하고 있습니다. 아래에서 문의 방법, 자주 묻는 질문, 지원 시간 등을 확인해 주세요.</p>\n");
      out.write("\n");
      out.write("            <h2>1. 문의 방법</h2>\n");
      out.write("            <p>우리는 다양한 채널을 통해 고객의 문의를 받고 있습니다. 아래 방법 중 편리한 방식으로 연락 주세요.</p>\n");
      out.write("            <div class=\"highlight\">\n");
      out.write("                <ul>\n");
      out.write("                    <li>이메일: <a href=\"mailto:support@insaplatform.com\">support@insaplatform.com</a></li>\n");
      out.write("                    <li>전화: 02-1234-5678 (평일 09:00~18:00)</li>\n");
      out.write("                    <li>온라인 문의: <a href=\"/contact-form\">문의 폼</a>을 통해 24시간 접수 가능</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <h2>2. 지원 시간</h2>\n");
      out.write("            <p>고객지원팀은 다음 시간 동안 운영됩니다. 긴급 문의는 이메일 또는 온라인 문의 폼을 이용해 주세요.</p>\n");
      out.write("            <ul>\n");
      out.write("                <li>운영 시간: 평일 09:00~18:00 (점심 시간: 12:00~13:00 제외)</li>\n");
      out.write("                <li>비운영 시간: 주말 및 공휴일</li>\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("            <h2>3. 자주 묻는 질문 (FAQ)</h2>\n");
      out.write("            <p>고객들이 자주 묻는 질문과 답변을 정리했습니다. 문의 전 확인해 보시면 빠르게 해결하실 수 있습니다.</p>\n");
      out.write("            <div class=\"highlight\">\n");
      out.write("                <ul>\n");
      out.write("                    <li><strong>Q: 회원 가입은 어떻게 하나요?</strong><br>A: 홈페이지 우측 상단의 \"회원 가입\" 버튼을 클릭하여 정보를 입력하시면 됩니다.</li>\n");
      out.write("                    <li><strong>Q: 비밀번호를 잊어버렸습니다.</strong><br>A: 로그인 페이지에서 \"비밀번호 찾기\"를 클릭하여 이메일로 재설정 링크를 받아보세요.</li>\n");
      out.write("                    <li><strong>Q: 채용 공고는 어디서 확인하나요?</strong><br>A: 메인 페이지의 \"채용 정보\" 섹션에서 최신 공고를 확인하실 수 있습니다.</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <h2>4. 기술 지원</h2>\n");
      out.write("            <p>서비스 이용 중 기술적인 문제가 발생한 경우, 아래 연락처로 문의해 주세요. 신속히 문제를 진단하고 해결 방안을 안내드립니다.</p>\n");
      out.write("            <div class=\"highlight\">\n");
      out.write("                <p>기술 지원팀<br>이메일: tech@insaplatform.com<br>전화: 02-9876-5432</p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <h2>5. 피드백</h2>\n");
      out.write("            <p>주식회사 인사플랫폼은 고객의 피드백을 소중히 생각합니다. 서비스 개선을 위한 제안이나 의견이 있다면 언제든지 알려주세요.</p>\n");
      out.write("            <ul>\n");
      out.write("                <li>피드백 접수: <a href=\"mailto:feedback@insaplatform.com\">feedback@insaplatform.com</a></li>\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("            <div class=\"footer\">\n");
      out.write("                <p>최종 업데이트: 2025년 5월 1일</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("	</main>\n");
      out.write("\n");
      out.write("	<!-- Footer -->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/jsp/Footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("	<script>\n");
      out.write("\n");
      out.write("	</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/MainPage/customerSupport.jsp(15,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/resources/css/Header.css");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/views/MainPage/customerSupport.jsp(17,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/resources/css/Footer.css");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }
}
