/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-30 07:41:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.MainPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1743573402475L));
    _jspx_dependants.put("jar:file:/D:/workspaces/pj/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 최성현 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>3부상조 - 비즈니스 플랫폼</title>\r\n");
      out.write("    <!-- 폰트 로드 -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Font Awesome for social icons -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\r\n");
      out.write("    <!-- CSS 파일 링크 -->\r\n");
      out.write("    <link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <!-- Header -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/jsp/Header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Content -->\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <!-- Visual Section -->\r\n");
      out.write("            <div class=\"visual\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"txt-box\">\r\n");
      out.write("                        <h2 class=\"txt-main\">\r\n");
      out.write("                            3부상조<span class=\"strong\">비즈니스 플랫폼</span>\r\n");
      out.write("                        </h2>\r\n");
      out.write("                        <p class=\"txt-sub\">\r\n");
      out.write("                            혁신적인 솔루션으로<br>당신의 비즈니스를 성장시키세요.\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Shortcut Section -->\r\n");
      out.write("            <div class=\"shortcut\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <ul class=\"shortcut-list clearfix\">\r\n");
      out.write("                        <li class=\"shortcut-list-item\"><a href=\"login\">\r\n");
      out.write("                                <h3 class=\"txt-main\">시작하기</h3>\r\n");
      out.write("                                <p class=\"txt-sub\">\r\n");
      out.write("                                    3부상조 플랫폼 테스트를 시작하기 위해<br> 계정을 등록하고 서비스를 경험하세요.\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <p class=\"img-box\">\r\n");
      out.write("                                    <span class=\"screen-hidden\"></span>\r\n");
      out.write("                                </p>\r\n");
      out.write("                        </a></li>\r\n");
      out.write("                        <li class=\"shortcut-list-item\"><a href=\"attendance\">\r\n");
      out.write("                                <h3 class=\"txt-main\">출, 퇴근 관리</h3>\r\n");
      out.write("                                <p class=\"txt-sub\">\r\n");
      out.write("                                    출근과 퇴근 시간을<br> 실시간으로 보고 편하게 등록하세요.\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <p class=\"img-box\">\r\n");
      out.write("                                    <span class=\"screen-hidden\"></span>\r\n");
      out.write("                                </p>\r\n");
      out.write("                        </a></li>\r\n");
      out.write("                        <li class=\"shortcut-list-item\"><a href=\"electronicpayment\">\r\n");
      out.write("                                <h3 class=\"txt-main\">전자 결제</h3>\r\n");
      out.write("                                <p class=\"txt-sub\">\r\n");
      out.write("                                    손쉽고 간편하게<br> 승인 요청을 넣어보세요.\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <p class=\"img-box\">\r\n");
      out.write("                                    <span class=\"screen-hidden\"></span>\r\n");
      out.write("                                </p>\r\n");
      out.write("                        </a></li>\r\n");
      out.write("                        <li class=\"shortcut-list-item\"><a href=\"notice\">\r\n");
      out.write("                                <h3 class=\"txt-main\">게시판</h3>\r\n");
      out.write("                                <p class=\"txt-sub\">\r\n");
      out.write("                                    자유롭게 하고싶은 얘기나<br> 올리고싶은 파일을 올려보세요\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <p class=\"img-box\">\r\n");
      out.write("                                    <span class=\"screen-hidden\"></span>\r\n");
      out.write("                                </p>\r\n");
      out.write("                        </a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Recent Posts Section -->\r\n");
      out.write("            <div class=\"article recent-posts\">\r\n");
      out.write("                <div class=\"container clearfix\">\r\n");
      out.write("                    <div class=\"txt-box\">\r\n");
      out.write("                        <span class=\"txt-sub2\">최근 소식</span>\r\n");
      out.write("                        <h3 class=\"txt-main\">게시판 업데이트</h3>\r\n");
      out.write("                        <p class=\"txt-sub\">3부상조 게시판의 최신 글을 확인하세요.</p>\r\n");
      out.write("                        <span class=\"txt-sub3\">최신 업데이트: 2025/04/24 00:00</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"graphic-box clearfix\">\r\n");
      out.write("                        <ul class=\"post-list\">\r\n");
      out.write("                            <li class=\"post-item\"><a\r\n");
      out.write("                                href=\"noticeone\">\r\n");
      out.write("                                    <h4 class=\"post-title\">2025년 상반기 워크숍 안내</h4>\r\n");
      out.write("                                    <p class=\"post-meta\">\r\n");
      out.write("                                        <span>작성자: 김관리</span> <span>작성일: 2025/04/23</span>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                            </a></li>\r\n");
      out.write("                            <li class=\"post-item\"><a\r\n");
      out.write("                                href=\"noticetwo\">\r\n");
      out.write("                                    <h4 class=\"post-title\">급여 관리 시스템 업데이트 공지</h4>\r\n");
      out.write("                                    <p class=\"post-meta\">\r\n");
      out.write("                                        <span>작성자: 박인사</span> <span>작성일: 2025/04/22</span>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                            </a></li>\r\n");
      out.write("                            <li class=\"post-item\"><a\r\n");
      out.write("                                href=\"noticethree\">\r\n");
      out.write("                                    <h4 class=\"post-title\">휴가 신청 프로세스 변경 안내</h4>\r\n");
      out.write("                                    <p class=\"post-meta\">\r\n");
      out.write("                                        <span>작성자: 이인사</span> <span>작성일: 2025/04/20</span>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                            </a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Info Step Section -->\r\n");
      out.write("            <div class=\"article info-step\">\r\n");
      out.write("                <div class=\"container clearfix\">\r\n");
      out.write("                    <div class=\"txt-box\">\r\n");
      out.write("                        <span class=\"txt-sub2\">3부상조</span>\r\n");
      out.write("                        <h3 class=\"txt-main\">이용 절차</h3>\r\n");
      out.write("                        <p class=\"txt-sub\">\r\n");
      out.write("                            간단한 절차로<br> 3부상조의 모든 서비스를<br> 이용할 수 있습니다.\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"graphic-box clearfix\">\r\n");
      out.write("                        <div class=\"div-step\">\r\n");
      out.write("                            <p class=\"step-txt\">\r\n");
      out.write("                                STEP<span class=\"step-num\">01</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"step-icon\">\r\n");
      out.write("                                <img src=\"resources/image/icons8-로그인-50.png\" alt=\"\">\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"step-txt-sub\">\r\n");
      out.write("                                3부상조 플랫폼에 로그인 및<br> 계정 등록\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"div-step\">\r\n");
      out.write("                            <p class=\"step-txt\">\r\n");
      out.write("                                STEP<span class=\"step-num\">02</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"step-icon\">\r\n");
      out.write("                                <img src=\"resources/image/icons8-서비스-50.png\" alt=\"\">\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"step-txt-sub\">\r\n");
      out.write("                                서비스 테스트 및<br> 기능 확인\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"div-step\">\r\n");
      out.write("                            <p class=\"step-txt\">\r\n");
      out.write("                                STEP<span class=\"step-num\">03</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"step-icon\">\r\n");
      out.write("                                <img src=\"resources/image/icons8-문서-서명-50.png\" alt=\"\">\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"step-txt-sub\">\r\n");
      out.write("                                3부상조 서비스<br> 약정 체결\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"div-step\">\r\n");
      out.write("                            <p class=\"step-txt\">\r\n");
      out.write("                                STEP<span class=\"step-num\">04</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"step-icon\">\r\n");
      out.write("                                <img src=\"resources/image/icons8-적용-스킨-타입-7-48.png\" alt=\"\">\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p class=\"step-txt-sub\">\r\n");
      out.write("                                운영 환경 적용 및<br> 서비스 시작\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Company Info Section -->\r\n");
      out.write("            <div class=\"article company-info\">\r\n");
      out.write("                <div class=\"container clearfix\">\r\n");
      out.write("                    <div class=\"txt-box\">\r\n");
      out.write("                        <span class=\"txt-sub2\">회사 정보</span>\r\n");
      out.write("                        <h3 class=\"txt-main\">3부상조를 찾아오세요</h3>\r\n");
      out.write("                        <p class=\"txt-sub\">당신의 비즈니스 파트너, 3부상조의 위치를 확인하세요.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"graphic-box clearfix\">\r\n");
      out.write("                        <div class=\"info-details\">\r\n");
      out.write("                            <p>\r\n");
      out.write("                                <strong>회사명:</strong> 3부상조 주식회사\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                <strong>주소:</strong> 서울특별시 마포구 백범로 23, 3층 (신수동, 케이터틀)\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                <strong>전화번호:</strong> 02-1234-5678\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                <strong>이메일:</strong> contact@3busangjo.com\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"map-container\">\r\n");
      out.write("                            <iframe\r\n");
      out.write("                                src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3162.803744693673!2d126.93840231521123!3d37.54999397980272!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x357c989d7c7e8b8b%3A0x9f5c8e2b5d9e6f1!2z7ISc7Jq47Yq567OE7IucIOyCrOyaqeygnOq1rCDrsLDsmrXroZwzMe2DkywgM-yKpO2DhOybkA!5e0!3m2!1sko!2skr!4v1698771234567!5m2!1sko!2skr\"></iframe>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Footer -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/jsp/Footer.jsp", out, false);
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/MainPage/index.jsp(15,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/resources/css/Header.css");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/views/MainPage/index.jsp(16,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/resources/css/Footer.css");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/views/MainPage/index.jsp(17,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/resources/css/index.css");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }
}
