/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-05-11 09:01:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.MainPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class privacyPolicy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1743573402475L));
    _jspx_dependants.put("jar:file:/D:/workspaces/pj/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("```jsp\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>개인정보처리방침</title>\n");
      out.write("    <!-- CSS 파일 링크 -->\n");
      out.write("    <link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        .privacy-container {\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif;\n");
      out.write("            background-color: #fff;\n");
      out.write("            color: #333;\n");
      out.write("            line-height: 1.6;\n");
      out.write("            max-width: 800px;\n");
      out.write("            margin: 120px auto 50px; /* 헤더 높이(80px) + 여백 조정 */\n");
      out.write("            padding: 40px;\n");
      out.write("            border-radius: 12px;\n");
      out.write("            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);\n");
      out.write("        }\n");
      out.write("        .privacy-container h1 {\n");
      out.write("            font-size: 2.2em;\n");
      out.write("            color: #2c3e50;\n");
      out.write("            text-align: center;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("        }\n");
      out.write("        .privacy-container h2 {\n");
      out.write("            font-size: 1.5em;\n");
      out.write("            color: #34495e;\n");
      out.write("            margin-top: 30px;\n");
      out.write("            border-bottom: 2px solid #3498db;\n");
      out.write("            padding-bottom: 10px;\n");
      out.write("        }\n");
      out.write("        .privacy-container p, .privacy-container li {\n");
      out.write("            font-size: 1em;\n");
      out.write("            color: #4a4a4a;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("        .privacy-container ul {\n");
      out.write("            padding-left: 20px;\n");
      out.write("        }\n");
      out.write("        .privacy-container li {\n");
      out.write("            list-style-type: disc;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("        .privacy-container .highlight {\n");
      out.write("            background-color: #e8f4f8;\n");
      out.write("            padding: 15px;\n");
      out.write("            border-left: 4px solid #3498db;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("            border-radius: 4px;\n");
      out.write("        }\n");
      out.write("        .privacy-container .footer {\n");
      out.write("            text-align: center;\n");
      out.write("            margin-top: 40px;\n");
      out.write("            font-size: 0.9em;\n");
      out.write("            color: #7f8c8d;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Header -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/jsp/Header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <main>\n");
      out.write("        <div class=\"privacy-container\">\n");
      out.write("            <h1>개인정보처리방침</h1>\n");
      out.write("            <p>주식회사 인사플랫폼(이하 \"회사\")은 이용자의 개인정보를 소중히 보호하기 위해 「개인정보보호법」 및 관련 법령을 준수하며, 아래와 같이 개인정보처리방침을 수립·공개합니다.</p>\n");
      out.write("\n");
      out.write("            <h2>1. 개인정보의 처리 목적</h2>\n");
      out.write("            <p>회사는 다음의 목적을 위해 개인정보를 처리합니다. 처리한 개인정보는 다음 목적 이외의 용도로는 사용되지 않습니다.</p>\n");
      out.write("            <ul>\n");
      out.write("                <li>회원 가입 및 관리: 회원제 서비스 제공, 본인 확인, 개인 식별</li>\n");
      out.write("                <li>서비스 제공: 채용 정보 제공, 인사 관리, 맞춤형 서비스 제공</li>\n");
      out.write("                <li>마케팅 및 광고: 이벤트 및 광고성 정보 제공, 이용자 분석</li>\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("            <h2>2. 처리하는 개인정보 항목</h2>\n");
      out.write("            <p>회사는 아래와 같은 개인정보를 수집·이용합니다.</p>\n");
      out.write("            <div class=\"highlight\">\n");
      out.write("                <ul>\n");
      out.write("                    <li>필수 항목: 이름, 이메일 주소, 연락처, 생년월일</li>\n");
      out.write("                    <li>선택 항목: 학력, 경력, 자격증</li>\n");
      out.write("                    <li>자동 수집 항목: IP 주소, 쿠키, 방문 기록</li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <h2>3. 개인정보의 보유 및 이용 기간</h2>\n");
      out.write("            <p>회사는 개인정보의 수집·이용 목적이 달성된 후에는 해당 정보를 지체 없이 파기합니다. 단, 아래의 경우에는 예외적으로 보관합니다.</p>\n");
      out.write("            <ul>\n");
      out.write("                <li>법령에 따라 보존해야 하는 경우: 전자상거래 등에서의 소비자 보호에 관한 법률(5년)</li>\n");
      out.write("                <li>회원 탈퇴 후 재가입 방지를 위해: 30일간 보관</li>\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("            <h2>4. 개인정보의 제3자 제공</h2>\n");
      out.write("            <p>회사는 이용자의 동의 없이 개인정보를 제3자에게 제공하지 않습니다. 다만, 법령에 따라 요구되는 경우에는 예외로 제공될 수 있습니다.</p>\n");
      out.write("\n");
      out.write("            <h2>5. 개인정보의 안전성 확보 조치</h2>\n");
      out.write("            <p>회사는 개인정보 보호를 위해 다음과 같은 조치를 취하고 있습니다.</p>\n");
      out.write("            <ul>\n");
      out.write("                <li>기술적 조치: 암호화, 방화벽 설치, 접근 통제</li>\n");
      out.write("                <li>관리적 조치: 내부 관리 계획 수립, 정기적 직원 교육</li>\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("            <h2>6. 이용자의 권리와 행사 방법</h2>\n");
      out.write("            <p>이용자는 언제든지 자신의 개인정보를 조회하거나 수정할 수 있으며, 삭제를 요청할 수 있습니다. 권리 행사는 아래 연락처로 요청해 주시기 바랍니다.</p>\n");
      out.write("            <div class=\"highlight\">\n");
      out.write("                <p>개인정보 보호 담당자: 김민수<br>연락처: privacy@insaplatform.com<br>전화: 02-1234-5678</p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <h2>7. 개인정보처리방침의 변경</h2>\n");
      out.write("            <p>본 방침은 법령 및 회사 정책에 따라 변경될 수 있으며, 변경 시 홈페이지를 통해 공지합니다.</p>\n");
      out.write("\n");
      out.write("            <div class=\"footer\">\n");
      out.write("                <p>시행일자: 2025년 5월 1일</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("    <!-- Footer -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/resources/jsp/Footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        // 필요한 경우 JavaScript 추가\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("```");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/MainPage/privacyPolicy.jsp(11,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/resources/css/Header.css");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/views/MainPage/privacyPolicy.jsp(12,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/resources/css/Footer.css");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }
}
